name: Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install deps
              run: npm ci

            - name: Build
              run: npm run build

            - name: Read version from manifest
              id: version
              run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

            - name: Zip dist contents
              run: |
                  cd dist
                  zip -r ../url-hyperlinker-${{ steps.version.outputs.version }}.zip .
                  cd -

            - name: Restore CRX private key
              shell: bash
              run: |
                  echo "${{ secrets.PRIVATE_KEY_BASE64 }}" | base64 -d > private.pem

            - name: Install crx3
              run: npm i -g crx3

            - name: Pack CRX with stable key
              run: crx3 dist --private-key private.pem -o url-hyperlinker.crx

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  body: Auto release
                  draft: false
                  prerelease: false
                  files: |
                      url-hyperlinker-${{ steps.version.outputs.version }}.zip
                      url-hyperlinker.crx
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
